### PR TITLE
New svg-icons

### PR DESCRIPTION
**Pull request by dellus**
Signed-off-by: dellus dellus@gmx.de

### CODE REVIEW

**Comment by r-a-v-a-s** [comment]
Thanks! :+1:

**Comment by r-a-v-a-s** [comment]
Something to note is that the pattern in the hatch icons isn't accepted by Qt.

**Comment by dellus** [comment]
Does this mean patterns can not be used generally and have to be drawn  
manually line by line or is just something wrong with the patterns in this  
case?

dellus

**Comment by r-a-v-a-s** [comment]
It might not be supported.

> Qt supports the static features of SVG 1.2 Tiny. ECMA scripts and DOM manipulation are currently not supported.

http://doc.qt.io/qt-5/svgrendering.html

The two forum questions I found didn't provide solutions.

**Pull request merged**
